language: objective-c
osx_image: xcode10.2
podfile: Example/Podfile

before_install:
    - brew update
    - pod repo update --silent

script:
    - set -o pipefail && xcodebuild test -workspace Example/Optik.xcworkspace -scheme Optik-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.1' | xcpretty
    - pod lib lint
